name = "macro-liquidity-dashboard"
main = "src/worker.ts"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "macro_liquidity"
database_id = "5ee92b9b-eb8e-4c34-9479-b0838fa113fb"
migrations_dir = "migrations"

[triggers]
crons = ["0 */3 * * *"]

[vars]
START_DATE = "2016-01-01"
